[package]
name = "stellarlib"
version = "0.1.0"
edition = "2021"

[dependencies]
stellar-strkey = "0.0.18"
ethnum = { version = "1.5.3" }
escape-bytes = { version = "0.1.1", default-features = false, features = [
    "alloc",
] }
hex = { version = "0.4.3", default-features = false, features = ["alloc"] }

[dev-dependencies]
csv = "1.4"
base64 = "0.23"
