# We provide a pre-built image to save you time, but if you want to build it yourself,
# you can copy https://github.com/overcat/ledger-devcontainer/blob/main/Dockerfile to the current
# folder to overwrite this file.
#
# More information: https://github.com/overcat/ledger-devcontainer

FROM ghcr.io/overcat/ledger-devcontainer:latest