name: ClusterFuzzLite cron tasks
on:
  workflow_dispatch:
    inputs:
      fuzz-seconds:
        description: "Number of seconds to run fuzzers"
        required: false
        default: "600"
  push:
    branches:
      - develop # Use your actual default branch here.
  schedule:
    - cron: "0 8 * * 1" # At 08:00 on Monday.
permissions: read-all
jobs:
  Fuzzing:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - mode: batch
            sanitizer: address
          - mode: batch
            sanitizer: undefined
          - mode: batch
            sanitizer: memory
          - mode: prune
            sanitizer: address
          - mode: coverage
            sanitizer: coverage
    steps:
      - name: Build Fuzzers (${{ matrix.mode }} - ${{ matrix.sanitizer }})
        id: build
        uses: google/clusterfuzzlite/actions/build_fuzzers@v1
        with:
          language: c # Change this to the language you are fuzzing.
          github-token: ${{ secrets.GITHUB_TOKEN }}
          sanitizer: ${{ matrix.sanitizer }}
          storage-repo: https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/lightsail-network/app-stellar-fuzz-corpus
          storage-repo-branch: main
          storage-repo-branch-coverage: gh-pages
      - name: Run Fuzzers (${{ matrix.mode }} - ${{ matrix.sanitizer }})
        id: run
        uses: google/clusterfuzzlite/actions/run_fuzzers@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fuzz-seconds: ${{ github.event.inputs.fuzz-seconds || '600' }} # Defaults to 10 minutes
          mode: ${{ matrix.mode }}
          sanitizer: ${{ matrix.sanitizer }}
          storage-repo: ${{ secrets.PERSONAL_ACCESS_TOKEN && format('https://{0}@github.com/lightsail-network/app-stellar-fuzz-corpus', secrets.PERSONAL_ACCESS_TOKEN) || '' }}
          storage-repo-branch: ${{ secrets.PERSONAL_ACCESS_TOKEN && 'main' || '' }}
          storage-repo-branch-coverage: ${{ secrets.PERSONAL_ACCESS_TOKEN && 'gh-pages' || '' }}
